#! /bin/sh

# Restore wallpaper
bash $HOME/.config/bspwm/.fehbg

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/bspwm/polybar/launch.sh

# set workspaces for both monitors

# monitor 1 covers all code based-materials
#  1. terminals
#  2. text editors
#  3. server management
#  4. 

# monitor 2 covers all utilities
#  -. Web Browser/Discord
#  -. File System
#  -. Settings
workspaces() {
    monitors=($(bspc query -M))
    bspc monitor ${monitors[0]} -d '' '' ''
    bspc monitor ${monitors[1]} -d '' '' 'ﭮ' ''
}
workspaces

bspc config border_width         4
bspc config window_gap           10
bspc config split_ratio          0.50

bspc config focused_border_color "#7aa2f7"
bspc config normal_border_color "#32344a"
bspc config active_border_color "#444b6a"

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

# fix pointer
xsetroot -cursor_name left_ptr

# for the sake of ease, workspaces 1, 2, 3, and 5 are not "ruled" workspaces. It is only 
# suggested that their respective functions be placed inside them. This is so, if a browser
# is open in workspace 4, a terminal can very quickly be opened on the same screen to test
# something without having to switch views to a separate monitor

# workspace 4 (Browser)
declare -a media=(firefox)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^4' follow=on focus=on; done

# workspace 6 (Discord)
declare -a media=(discord)
for i in ${media[@]}; do
    bspc rule -a $i desktop='^6' follow=on focus=on; done

# workspace 7 (Settings)
declare -a settings=(GParted Lxappearance Lxtask Lxrandr Arandr \
Pavucontrol Xfce4-settings-manager)
for i in ${settings[@]}; do
    bspc rule -a $i desktop='^7' follow=on focus=on; done


# floating windows
declare -a floats=(Alafloat Lxappearance Arandr \
Viewnior Pcmanfm feh Nm-connection-editor Matplotlib Yad)
for i in ${floats[@]}; do
  bspc rule -a $i state=floating follow=on focus=on; done

## Autostart

# Kill if already running
killall -9 picom sxhkd dunst xfce4-power-manager ksuperkey eww

# Launch Conkeww
# sed -i "s/colors\/color-.*/colors\/color-tokyo.yuck\")/g" $HOME/.config/conkeww/eww.yuck
# eww --config $HOME/.config/conkeww/ open conkeww-main

# Launch notification daemon
dunst -config $HOME/.config/bspwm/dunstrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
    /usr/lib/xfce-polkit/xfce-polkit &
fi

# Launch keybindings daemon
sxhkd &

# Enable power management
xfce4-power-manager &

# Start udiskie
udiskie &

# start compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/bspwm/picom.conf &

# replace neovim colorscheme
sed -i "s/theme =.*$/theme = \"tokyonight\",/g" $HOME/.config/nvim/lua/chadrc.lua

# change xfce4-terminal colorscheme
XFCE_TERM_PATH="$HOME/.config/xfce4/terminal"
cp "$XFCE_TERM_PATH"/colorschemes/tokyo-night "$XFCE_TERM_PATH"/terminalrc
